-- MySQL Script generated by MySQL Workbench
-- Sun 13 Nov 2016 11:39:20 PM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nodejs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nodejs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nodejs` DEFAULT CHARACTER SET utf8 ;
USE `nodejs` ;

-- -----------------------------------------------------
-- Table `nodejs`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nodejs`.`Users` ;

CREATE TABLE IF NOT EXISTS `nodejs`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `hash` VARCHAR(255) NULL DEFAULT NULL,
  `authKey` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `token_UNIQUE` (`authKey` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nodejs`.`Notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nodejs`.`Notes` ;

CREATE TABLE IF NOT EXISTS `nodejs`.`Notes` (
  `id` INT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `userID` INT(11) NOT NULL,
  UNIQUE INDEX `unique_id` (`id` ASC),
  INDEX `fk_Notes_1_idx` (`userID` ASC),
  CONSTRAINT `fk_Notes_1`
    FOREIGN KEY (`userID`)
    REFERENCES `nodejs`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
